spring:
  datasource:
    url: jdbc:mysql://ec2-43-200-4-240.ap-northeast-2.compute.amazonaws.com:33/gss
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

server:
  port: 9000

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /sw
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match: