spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/gss
    username: postgres
    password: root
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 9000


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /sw
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)